export { LoginPage } from "./LoginPage";
export { RegisterPage } from "./RegisterPage";
export { RubricsPage } from "./RubricsPage";
export { NewsPage } from "./NewsPage";
export { EventsPage } from "./EventsPage";
export { IdeasPage } from "./IdeasPage";
export { ProfilePage } from "./ProfilePage";
export { VacationPage } from "./VacationPage";
export { ShopPage } from "./ShopPage";
